# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    file_path: %kernel.root_dir%/../web
    file_web_path: /uploads

services:
    image.uploader:
        class: AppBundle\File\FileUploader
        arguments:
            - %file_path%%file_web_path%
            - %file_web_path%
    app.wit:
        class: AppBundle\Service\WitImpl
